### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by mango-buff**
Create zh_cn.json.
@starforcraft Seek merger.

### CODE REVIEW

**Comment by starforcraft** [comment]
Thanks!

**Comment by mango-buff** [comment]
> Thanks!

Can you release 1.19.2 according to this Pull requests? I only saw you release 1.18.2 and 1.19.3 on curseforge.

**Comment by starforcraft** [comment]
Here: https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/4364478

**Comment by mango-buff** [comment]
> Here: https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/4364478

Thank you.

**Pull request merged**
